version: '3.9'

services:
  mysql:
    container_name: mysql_kinote
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: kinote_db
    ports:
      - "3306:3306"
    volumes:
      - api_kinote_mysql_data:/var/lib/mysql

  adminer:
    container_name: adminer_kinote
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  app:
    container_name: kinote_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:12345@mysql:3306/kinote_db
      - JWT_SECRET=supersecretkey123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GMAIL_SMTP_HOST=${GMAIL_SMTP_HOST}
      - GMAIL_SMTP_PORT=${GMAIL_SMTP_PORT}
      - GMAIL_SMTP_USER=${GMAIL_SMTP_USER}
      - GMAIL_SMTP_PASS=${GMAIL_SMTP_PASS}
      - VERIFY_EMAIL_FROM=${VERIFY_EMAIL_FROM}
      - VERIFY_EMAIL_TO=${VERIFY_EMAIL_TO}
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - mysql

volumes:
  api_kinote_mysql_data:
